### ISSUE TITLE
Ошибка при запуске!

### ISSUE THREAD

**Issue by ghost** [trananhtuan/acestream-armv7-docker#1]
Ошибка при запуске: UnboundLocalError: local variable 'aliases' referenced before assignment
И crash :-(

**Comment by ghost** [comment]
_вот такая вот ошибка:_

**# docker run --security-opt seccomp=profile.json --name acestream-armv7 --restart=always --network=host trananhtuan/acestream-armv7**
Using python 2.7.16+ .....
Try to load conf file: /acestream.engine/acestream.conf
Start AceStream engine .....
Load library: /acestream.engine/eggs/six-1.12.0-py2.7.egg
Load library: /acestream.engine/eggs/Routes-2.4.1-py2.7.egg
Load library: /acestream.engine/eggs/repoze.lru-0.7-py2.7.egg
Load library: /acestream.engine/eggs/html5lib-1.1.dev0-py2.7.egg
Load library: /acestream.engine/eggs/webencodings-0.6.dev0-py2.7.egg
Load library: /acestream.engine/eggs/urllib3-1.25.2-py2.7.egg
Load library: /acestream.engine/eggs/websocket_client-0.56.0-py2.7.egg
Load library: /acestream.engine/eggs/singledispatch-3.4.0.3-py2.7.egg
Load library: /acestream.engine/eggs/certifi-2019.3.9-py2.7.egg
Load library: /acestream.engine/eggs/ipaddr-2.2.0-py2.7.egg
Load library: /acestream.engine/eggs/chardet-4.0.0-py2.7.egg
Load library: /acestream.engine/eggs/idna-2.8-py2.7.egg
Load library: /acestream.engine/eggs/futures-3.2.0-py2.7.egg
Load library: /acestream.engine/eggs/requests-2.22.0-py2.7.egg
Load library: /acestream.engine/eggs/xmltodict-0.12.0-py2.7.egg
Load library: /acestream.engine/eggs/ipwhois-1.1.0-py2.7.egg
Load library: /acestream.engine/eggs/iso8601-0.1.12-py2.7.egg
Load library: /acestream.engine/eggs/enum34-1.1.6-py2.7.egg
Load library: /acestream.engine/eggs/opengraph-0.5-py2.7.egg
Load library: /acestream.engine/eggs/beautifulsoup4-4.7.1-py2.7.egg
2019-07-13 05:39:01,133|MainThread|acestream|language=en
2019-07-13 05:39:01,134|MainThread|acestream|exec_dir='/acestream.engine'
2019-07-13 05:39:01,134|MainThread|acestream|logs_dir='/acestream.engine'
2019-07-13 05:39:01,135|MainThread|acestream|install_dir='/acestream.engine'
2019-07-13 05:39:01,145|MainThread|acestream|init segmenter done: log_path=/acestream.engine/segmenter.log
2019-07-13 05:39:01,145|MainThread|acestream|platform=android
2019-07-13 05:39:01,147|MainThread|acestream|app=acestream
2019-07-13 05:39:01,147|MainThread|acestream|version=3.1.46 code=3014600 revision=98928c5 date=2019-06-27
2019-07-13 05:39:01,147|MainThread|acestream|use_local_db=True
2019-07-13 05:39:01,148|MainThread|acestream|use_m2crypto=False
2019-07-13 05:39:01,149|MainThread|acestream|is_gui_mode=0
2019-07-13 05:39:01,150|MainThread|acestream|enable debug: 0
2019-07-13 05:39:01,176|MainThread|acestream|get_default_api_version: 2
2019-07-13 05:39:01,177|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2019-07-13 05:39:01,178|MainThread|acestream.coreapp|state_dir='/acestream.engine/.ACEStream'
2019-07-13 05:39:01,188|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2019-07-13 05:39:01,189|MainThread|acestream|enable debug: 0
2019-07-13 05:39:01,203|MainThread|acestream.coreapp|cannot load session config, use default
2019-07-13 05:39:04,293|MainThread|acestream.guessip|get_wan_ip: error
Traceback (most recent call last):
  File "./ACEStream/Core/NATFirewall/guessip.py", line 19, in get_my_wan_ip
  File "/acestream.engine/eggs/requests-2.22.0-py2.7.egg/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/acestream.engine/eggs/requests-2.22.0-py2.7.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/acestream.engine/eggs/requests-2.22.0-py2.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/acestream.engine/eggs/requests-2.22.0-py2.7.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/acestream.engine/eggs/requests-2.22.0-py2.7.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb47663d0>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))
2019-07-13 05:39:04,305|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:33235
2019-07-13 05:39:04,306|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2019-07-13 05:39:04,306|MainThread|acestream.LM|listen on 8621
2019-07-13 05:39:04,307|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database '/acestream.engine/.ACEStream/sqlite/torrentstream.sdb'
2019-07-13 05:39:04,426|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2019-07-13 05:39:04,429|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 347, in 
  File "core.c", line 1362, in 
  File "./ACEStream/Video/VideoServer.py", line 70, in __init__
  File "/home/pasha/python-for-android/python-build/python_arm/python-ext/python/SocketServer.py", line 420, in __init__
  File "/home/pasha/python-for-android/python-build/python_arm/python-ext/python/BaseHTTPServer.py", line 110, in server_bind
  File "./ACEStream/socket.py", line 84, in getfqdn
UnboundLocalError: local variable 'aliases' referenced before assignment
Exception in thread Thread-17 (most likely raised during interpreter shutdown):

**Comment by ghost** [comment]
решил добавлением записей в /etc/hosts. до этого он был пуст.
